name: 🐞 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
assignees: ["davydev"]
body:
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      placeholder: Briefly describe the issue
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Go to...\n2. Click...\n3. See error"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should happen instead?

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      placeholder: Paste any logs or attach screenshots
      render: bash

  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: e.g. v1.2.3
