name: 💡 Feature Request
description: Suggest an improvement or new capability
title: "[FEATURE] "
labels: ["enhancement"]
assignees: ["davydev"]
body:
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: One-liner of what you’re requesting
    validations:
      required: true

  - type: dropdown
    id: app
    attributes:
      label: Affected App
      description: Where would this feature apply?
      options:
        - Panels
        - Phones
        - Maintenance
        - Connect
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case / Motivation
      description: What’s the problem you're trying to solve or improve?
      placeholder: "I’d like to be able to..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe your idea clearly.
      placeholder: "The system could provide..."

  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to your workflow?
      options:
        - 🔴 Critical – urgently needed for core functionality
        - 🟠 High – would significantly improve operations
        - 🟡 Nice to Have – convenient but not essential
        - ⚪ Low – minimal impact or experimental
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or competing ideas?
      placeholder: "I’ve tried..."

  - type: input
    id: related
    attributes:
      label: Related Issues or Links
      placeholder: e.g., #12 or https://github.com/YOUR_REPO/issues/456

  - type: input
    id: device
    attributes:
      label: Device Model (if relevant)
      placeholder: e.g., iPad 9th Gen, Samsung Galaxy A50

  - type: input
    id: os
    attributes:
      label: OS Version (if relevant)
      placeholder: e.g., iOS 17.4, Android 13

  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Add anything else that might help clarify your request.
      placeholder: Attach mockups, diagrams, or other notes.
