name: Move Issues to Private Repo

on:
  issues:
    types: [opened]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to private repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const issue = context.payload.issue;
            const sourceRepo = context.repo.repo;
            const sourceOwner = context.repo.owner;
            const destOwner = "ArquellaLtd";
            const destRepo = "ArquellaDevTracker";

            const issueTitle = `[From ${sourceRepo}] ${issue.title}`;
            const issueBody = `**Original author:** @${issue.user.login}\n\n**Original issue URL:** ${issue.html_url}\n\n---\n\n${issue.body}`;

            // Create issue in private repo
            const newIssue = await github.rest.issues.create({
              owner: destOwner,
              repo: destRepo,
              title: issueTitle,
              body: issueBody
            });

            // Optionally close the original issue and leave a comment
            await github.rest.issues.createComment({
              owner: sourceOwner,
              repo: sourceRepo,
              issue_number: issue.number,
              body: `Thanks for submitting. This issue has been moved to our private tracker.`
            });

            await github.rest.issues.update({
              owner: sourceOwner,
              repo: sourceRepo,
              issue_number: issue.number,
              state: "closed"
            });
